// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
		int nTimes = Integer.parseInt(args[0]);
		int bigger = 0;
		int smallerOrEqual = 0;
		//runs the loop n times to simulate the random function
		for (int i = 0; i < nTimes; i++) {
			if (Math.random() > 0.5) {
				bigger++;
			} else {
				smallerOrEqual++;
			}
		}
				System.out.println("> 0.5: " + bigger + " times");
				System.out.println("<= 0.5: " + smallerOrEqual + " times");		
			// prints the value when both counters are bigger than 0
			if (smallerOrEqual > 0 && bigger > 0) {
				if (bigger > smallerOrEqual) {
					System.out.println ("Ratio: " + (double) smallerOrEqual / bigger );
				}
				else{
						System.out.println ("Ratio: " + (double) bigger / smallerOrEqual);
				}
			}
	}
}
