// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
		int nTimes = Integer.parseInt(args[0]);
		int bigger = 0;
		int smallerAndEqual = 0;
		//runs the loop n times to simulate the random function
		for (int i = 0; i < nTimes; i++) {
			if (Math.random() > 0.5) {
				bigger++;
			} else {
				smallerAndEqual++;
			}
		}
				System.out.println("> 0.5: " + bigger + " times");
				System.out.println("<= 0.5: " + smallerAndEqual + " times");		
			// prints the value when both counters are bigger than 0
			if (smallerAndEqual > 0 && bigger > 0) {
				System.out.println( "Ratio: " +  (double) bigger / smallerAndEqual);
			}
	}
}
